repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        language: python
        types: [ python ]
        pass_filenames: true
        files: ^src/.+
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.3.0
    hooks:
      - id: black
        types: [ python ]
        pass_filenames: true
        files: ^src/.+
