name: "tests"

on:
  push:
    branches: [ master ]
    paths: [ src, tests ]
  pull_request:
    branches: [ master ]

jobs:

  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]

    steps:
    - uses: actions/checkout@v4

    - name: Pre-commit hooks
      uses: pre-commit/action@v3.0.1

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        cache: pip
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        pip install pip setuptools wheel

    - name: Test
      run: |
        pip install -e .[test]
        pytest
